### ISSUE TITLE
consider up key for rotation

### ISSUE THREAD

**Issue by francisdb** [yonigibbs/yaet#8]
most Tetris versions I played allow using up for clockwise rotation

**Comment by yonigibbs** [comment]
Hey @francisdb. Thanks for logging the issue! I believe what you're looking for can already be done: on the main screen click the `Settings` button, then click on the current key binding for the "rotate clockwise" action ("X" initially). You'll then be able to assign any key you want. This is saved to local storage so once you've done it once it should persist for that browser. Let me know if you come across any problems with this.
